name: Digital artist
favicon: null
layout_spectrum: 0.880345
typography_spectrum: 0.53096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d97b21'
    - '#3f7b00'
    - '#a90000'
    - '#d3cf35'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
