name: Digital artist
favicon: null
layout_spectrum: 0.78148
typography_spectrum: 0.53096
title: Kristinn Gudmundsson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060000'
    - '#520400'
    - '#a31d02'
    - '#730b02'
    - '#bb2b06'
  brandStrength: 0.25
  lightness: 0.6924178630579263
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
