analytics: {}
color:
  brandColors:
    - '#060000'
    - '#520400'
    - '#a31d02'
    - '#730b02'
    - '#bb2b06'
  brandStrength: 0
  lightness: 0.1875
  rhythmicContrast: 0.25
  saturation: 0.3125
cta: {}
layout_spectrum: 0.880345
name: Digital artist
opengraph: {}
purpose: []
typography_spectrum: 0.53096
